services:
  linear-assistant:
    stop_grace_period: "1s"
    build:
      context: ./linear-assistant-ts
    env_file:
      - .env
    environment:
      ALLOWED_EMAILS: "dexter@humanlayer.dev,austin@humanlayer.dev,sundeep@humanlayer.dev,dan@humanlayer.dev"
      DEBUG_DISABLE_WEBHOOK_VERIFICATION: "true"
      HUMANLAYER_API_KEY_NAME: LINEAR_ASSISTANT_HUMANLAYER_API_KEY
    volumes:
      - ./linear-assistant-ts/src:/app/src
      - ./linear-assistant-ts/package.json:/app/package.json
      - ./linear-assistant-ts/package-lock.json:/app/package-lock.json
      - ./linear-assistant-ts/tsconfig.json:/app/tsconfig.json
    command:
      - /bin/sh
      - -c
      - |
        npm run dev-reload-debug
    ports:
      - "8000:8000"
      - "5858:5858"
  
  deploybot:
    stop_grace_period: "1s"
    build:
      context: ./deploybot-ts
    env_file:
      - .env
    environment:
      ALLOWED_EMAILS: "dexter@humanlayer.dev,austin@humanlayer.dev,sundeep@humanlayer.dev,dan@humanlayer.dev"
      DEBUG_DISABLE_WEBHOOK_VERIFICATION: "true"
      HUMANLAYER_API_KEY_NAME: DEPLOYBOT_HUMANLAYER_API_KEY
    ports:
      - "8001:8000"
    depends_on:
      - redis
    volumes:
      - ./deploybot-ts/src:/app/src
      - ./deploybot-ts/package.json:/app/package.json
      - ./deploybot-ts/package-lock.json:/app/package-lock.json
      - ./deploybot-ts/tsconfig.json:/app/tsconfig.json
    command:
      - /bin/sh
      - -c
      - |
        npm run dev-reload
  
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6378:6379"
    volumes:
      - "./redis-data:/data"
